In [1]:
import numpy as np
import pandas as pd

# UFO Sightings Analysis with NumPy

## Objective

In this notebook, I use NumPy to analyze a cleaned UFO sightings dataset. The goals are to:

- Learn NumPy arrays
- Compute descriptive statistics
- Explore numerical features
- Detect outliers
- Normalize data
- Prepare features for future quantum computing experiments with Qiskit

In [2]:
clean_df = pd.read_csv('../data/processed/ufo_clean.csv')

In [4]:
clean_df.head()
clean_df.info()
clean_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80302 entries, 0 to 80301
Data columns (total 15 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Date_time                        80302 non-null  object 
 1   city                             80302 non-null  object 
 2   state/province                   74510 non-null  object 
 3   country                          80302 non-null  object 
 4   UFO_shape                        80302 non-null  object 
 5   length_of_encounter_seconds      80299 non-null  float64
 6   described_duration_of_encounter  80302 non-null  object 
 7   description                      80302 non-null  object 
 8   date_documented                  80302 non-null  object 
 9   latitude                         80302 non-null  float64
 10  longitude                        80302 non-null  float64
 11  year                             80302 non-null  int64  
 12  month             

(80302, 15)

In [5]:
#converting the values to numpy

duration = clean_df['length_of_encounter_seconds'].to_numpy()

latitude = clean_df["latitude"].to_numpy()


longitude = clean_df["longitude"].to_numpy()

In [ ]:
type(duration)


80302

In [7]:
duration.dtype


dtype('float64')

In [8]:
duration.shape


(80302,)

In [9]:
duration.ndim


1

In [10]:
duration.size

80302

In [11]:
duration[:10]

array([2700., 7200.,   20.,   20.,  900.,  300.,  180., 1200.,  180.,
        120.])

In [12]:
duration[-10:]

array([  15.,   60.,  120.,  180.,   20.,  600., 1200., 1200.,    5.,
       1020.])

In [13]:
duration[100:110]

array([ 10.,  60., 240., 180., 300., 120., 300., 900.,  60.,  30.])

In [14]:
#stepping through the array
duration[::1000]

array([2.7000e+03, 1.2000e+02, 1.0000e+00, 9.0000e+02, 6.0000e+02,
       3.6000e+03, 1.5000e+01, 7.2000e+02, 1.2000e+02, 1.8000e+02,
       5.0000e+00, 1.5000e+01, 6.0000e+02, 4.0000e+00, 1.8000e+03,
       2.4000e+03, 9.0000e+02, 3.0000e+00, 3.0000e+00, 7.2000e+03,
       3.0000e+02, 5.4000e+02, 6.0000e+01, 1.8000e+03, 1.0000e+01,
       3.0000e+02, 6.0000e+02, 3.6000e+03, 1.0800e+04, 5.0000e+00,
       7.2000e+03, 2.4000e+03, 1.2000e+02, 3.0000e+01, 1.8000e+02,
       8.0000e+00, 3.5000e+01, 4.0000e+00, 6.0000e+01, 1.8000e+02,
       3.0000e+02, 1.8000e+02, 1.5000e+01, 4.2000e+03, 3.0000e+02,
       3.0000e+02, 4.0000e+01, 1.2096e+06, 4.2000e+02, 3.0000e+02,
       2.0000e+00, 1.2000e+02, 3.0000e+01, 9.0000e+01, 1.2000e+02,
       3.0000e+01, 3.0000e+01, 3.0000e+02, 3.0000e+02, 6.0000e+02,
       1.8000e+02, 4.0000e+00, 1.2000e+02, 2.4000e+02, 1.5000e+01,
       2.0000e+00, 1.8000e+02, 1.2000e+03, 1.2000e+02, 1.8000e+03,
       1.2000e+02, 3.0000e+02, 1.8000e+02, 1.5000e+01, 6.0000e

In [15]:
np.nanmean(duration)

np.float64(9020.29995343653)

In [16]:
np.nanmedian(duration)

np.float64(180.0)

In [17]:
np.nanstd(duration)

np.float64(620340.335945301)

In [18]:
np.nanmin(duration)

np.float64(0.001)

In [19]:
np.nanmax(duration)

np.float64(97836000.0)

In [20]:
np.nanvar(duration)

np.float64(384822132400.7289)

In [22]:
valid_duration = duration[~np.isnan(duration)]

In [23]:
np.percentile(valid_duration , 25)

np.float64(30.0)

In [25]:
np.percentile(valid_duration , 50)

np.float64(180.0)

In [26]:
np.percentile(valid_duration , 75)

np.float64(600.0)

In [27]:
np.percentile(valid_duration ,90)

np.float64(1800.0)

In [28]:
np.percentile(valid_duration, 95)

np.float64(3600.0)

In [29]:
np.percentile(valid_duration, 99)

np.float64(14400.0)

In [30]:
long_duration = duration > 3600

In [31]:
np.sum(long_duration)

np.int64(3200)

In [32]:
duration[long_duration]

array([ 7200., 14400.,  7200., ...,  5400.,  7200., 10800.], shape=(3200,))

In [33]:
short_duration = duration < 10
duration[short_duration]

array([3., 2., 8., ..., 8., 3., 5.], shape=(9987,))

# Now we detect outliers

In [34]:
Q1 =np.percentile(valid_duration , 25)
Q3 = np.percentile(valid_duration , 75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR


In [35]:
outliers = valid_duration[
    (valid_duration < lower) |
    (valid_duration > upper)
]

In [36]:
len(outliers)

10498

In [37]:
len(outliers) /len(valid_duration) * 100

13.073637280663519

## We now use normalisation to normalise the valid duration

In [43]:
normalized = (
    valid_duration - np.min(valid_duration) 
    ) / (
        np.max(valid_duration) - np.min(valid_duration)
    )


In [44]:
normalized.min()

np.float64(0.0)

In [46]:
normalized.max()

np.float64(1.0)

# We are building a feature matrix

In [49]:
features = clean_df[
[
    "latitude",
    'longitude',
    'length_of_encounter_seconds'
]

].dropna()

In [50]:
x = features.to_numpy()

In [51]:
x.shape

(80299, 3)

In [52]:
x.dtype

dtype('float64')

In [53]:
x[:5]

array([[ 2.98830556e+01, -9.79411111e+01,  2.70000000e+03],
       [ 2.93842100e+01, -9.85810820e+01,  7.20000000e+03],
       [ 5.32000000e+01, -2.91666700e+00,  2.00000000e+01],
       [ 2.89783333e+01, -9.66458333e+01,  2.00000000e+01],
       [ 2.14180556e+01, -1.57803611e+02,  9.00000000e+02]])

## Reflection

Using NumPy made numerical analysis much faster and cleaner than working with raw Python lists. I learned how to convert Pandas objects into NumPy arrays, compute descriptive statistics, filter data with Boolean indexing, detect outliers using the IQR method, normalize numerical features, and prepare a feature matrix. These processed numerical features will be used in the next notebook to explore quantum computing concepts with Qiskit.